# Generated by Django 5.0.3 on 2025-04-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_wedding_user_alter_wedding_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
