# Generated by Django 5.0.3 on 2025-04-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_guest_id_alter_wedding_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
